package_rename_config:
  android:
    app_name: {{ app_name }}
    package_name: {{ android_package_name }}
    override_old_package: {{override_old_package}}
    lang: kotlin
  ios:
    app_name: {{ app_name }}
    package_name: {{ ios_package_name }}
  web:
    app_name: {{ app_name }}
    description: {{ description }}
    bundle_name: {{ package_name }}
