name: webtrit_build_phone_tools

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Target platform for build'
        required: true
        default: 'windows' # or 'windows', 'linux', 'macos'
      branch:
        description: 'Branch to checkout'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        platform: [linux, macos, windows]
        exclude:
          - os: ubuntu-latest
            platform: macos
          - os: ubuntu-latest
            platform: windows
          - os: macos-latest
            platform: linux
          - os: macos-latest
            platform: windows
          - os: windows-latest
            platform: linux
          - os: windows-latest
            platform: macos

    steps:
      - name: Checkout source code
        if: matrix.platform == github.event.inputs.platform
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Dart SDK
        if: matrix.platform == github.event.inputs.platform
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: Show files in the repository
        if: matrix.platform == github.event.inputs.platform
        run: ls -al

      - name: Install dependencies
        if: matrix.platform == github.event.inputs.platform
        run: dart pub get

      - name: Build executable
        if: matrix.platform == github.event.inputs.platform
        run: |
          if [ "${{ matrix.platform }}" == "windows" ]; then
            dart compile exe bin/webtrit_phone_tools.dart -o build/${{ matrix.output }}
          elif [ "${{ matrix.platform }}" == "linux" ]; then
            dart compile exe bin/webtrit_phone_tools.dart -o build/${{ matrix.output }}
          elif [ "${{ matrix.platform }}" == "macos" ]; then
            dart compile exe bin/webtrit_phone_tools.dart -o build/${{ matrix.output }}
          else
            echo "Unsupported platform"
            exit 1

      - name: Upload build artifact
        if: matrix.platform == github.event.inputs.platform
        uses: actions/upload-artifact@v3
        with:
          name: dart-cli-build-${{ matrix.platform }}
          path: build/${{ matrix.output }}

      - name: Provide download link
        if: matrix.platform == github.event.inputs.platform
        run: |
          echo "Download the build artifact at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"
