name: webtrit_build_phone_tools

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Target platform for build'
        required: true
        default: 'windows' # or 'windows', 'linux', 'macos'
      branch:
        description: 'Branch to checkout'
        required: true
        default: 'main'

env:
  # COMMON DTO DEPENDENCY
  # -----------------

  # Repository consts ans location
  REPOSITORY_DEPENDENCY_COMMON_NAME: WebTrit/webtrit_phone_configurator_common
  REPOSITORY_DEPENDENCY_COMMON_BRANCH: ${{ github.event.inputs.commonDependencySourceBranch }}
  REPOSITORY_DEPENDENCY_COMMON_OUTPUT_DIR: webtrit_phone_configurator_common
  # -----------------

  # Repository consts ans location
  REPOSITORY_DEPENDENCY_TOOLS_NAME: WebTrit/webtrit_phone_tools
  REPOSITORY_DEPENDENCY_TOOLS_BRANCH: ${{ github.event.inputs.phoneConfiguratorToolSourceBranch }}
  REPOSITORY_DEPENDENCY_TOOLS_OUTPUT_DIR: webtrit_phone_tools
  # -----------

  # COMMON CONFIGURATION
  # --------------------

  # Paths
  WORKING_DIRECTORY: webtrit


jobs:
  filter_platform:
    runs-on: ubuntu-latest
    outputs:
      selected_platform: ${{ steps.set_output.outputs.platform }}
    steps:
      - name: Set selected platform
        id: set_output
        run: echo "::set-output name=platform::${{ github.event.inputs.platform }}"

  build:
    runs-on: ${{ matrix.os }}
    needs: filter_platform

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            output: webtrit_phone_tools
          - os: macos-latest
            platform: macos
            output: webtrit_phone_tools
          - os: windows-latest
            platform: windows
            output: webtrit_phone_tools.exe
      fail-fast: false

    steps:
      - name: Get tools repository
        uses: actions/checkout@v3
        with:
          repository: ${{env.REPOSITORY_DEPENDENCY_TOOLS_NAME}}
          ref: ${{env.REPOSITORY_DEPENDENCY_TOOLS_BRANCH}}
          path: ${{env.WORKING_DIRECTORY }}/${{ env.REPOSITORY_DEPENDENCY_TOOLS_OUTPUT_DIR }}

      - name: Get common repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ${{env.REPOSITORY_DEPENDENCY_COMMON_NAME}}
          ref: ${{env.REPOSITORY_DEPENDENCY_COMMON_BRANCH}}
          path: ${{env.WORKING_DIRECTORY }}/${{ env.REPOSITORY_DEPENDENCY_COMMON_OUTPUT_DIR }}

      - name: Setup Dart SDK
        if: matrix.platform == needs.filter_platform.outputs.selected_platform
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: Get dependency for tools repository
        working-directory: ${{env.WORKING_DIRECTORY }}
        run: |
          cd $REPOSITORY_DEPENDENCY_TOOLS_OUTPUT_DIR
          dart pub get

      - name: Build executable
        if: matrix.platform == needs.filter_platform.outputs.selected_platform
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          if [ "${{ matrix.platform }}" == "windows" ]; then
            dart compile exe bin/webtrit_phone_tools.dart -o build/${{ matrix.output }}
          elif [ "${{ matrix.platform }}" == "linux" ]; then
            dart compile exe bin/webtrit_phone_tools.dart -o build/${{ matrix.output }}
          elif [ "${{ matrix.platform }}" == "macos" ]; then
            dart compile exe bin/webtrit_phone_tools.dart -o build/${{ matrix.output }}
          else
            echo "Unsupported platform"
            exit 1

      - name: Upload build artifact
        if: matrix.platform == needs.filter_platform.outputs.selected_platform
        uses: actions/upload-artifact@v3
        with:
          name: dart-cli-build-${{ matrix.platform }}
          path: ${{ github.workspace }}/${{env.WORKING_DIRECTORY }}/${{env.REPOSITORY_DEPENDENCY_TOOLS_OUTPUT_DIR}}/build/${{ matrix.output }}

      - name: Provide download link
        if: matrix.platform == needs.filter_platform.outputs.selected_platform
        run: |
          echo "Download the build artifact at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"